select * from customer
limit 20;

ALTER TABLE customer ADD COLUMN age_group TEXT;



ALTER TABLE customer RENAME COLUMN "Gender" TO gender;
ALTER TABLE customer 
  RENAME COLUMN "Customer ID" TO customer_id;
ALTER TABLE customer 
  RENAME COLUMN "Age" TO age;

ALTER TABLE customer 
  RENAME COLUMN "Item Purchased" TO item_purchased;
ALTER TABLE customer 
  RENAME COLUMN "Category" TO category;
ALTER TABLE customer 
  RENAME COLUMN "Purchase Amount (USD)" TO purchase_amount;
ALTER TABLE customer 
  RENAME COLUMN "Location" TO location;
ALTER TABLE customer 
  RENAME COLUMN "Size" TO size;
ALTER TABLE customer 
  RENAME COLUMN "Color" TO color;
ALTER TABLE customer 
  RENAME COLUMN "Season" TO season;
ALTER TABLE customer 
  RENAME COLUMN "Review Rating" TO review_rating;
ALTER TABLE customer 
  RENAME COLUMN "Subscription Status" TO subscription_status;
ALTER TABLE customer 
  RENAME COLUMN "Shipping Type" TO shipping_type;
ALTER TABLE customer 
  RENAME COLUMN "Discount Applied" TO discount_applied;
ALTER TABLE customer 
  RENAME COLUMN "Promo Code Used" TO promo_code_used;
ALTER TABLE customer 
  RENAME COLUMN "Previous Purchases" TO previous_purchases;
ALTER TABLE customer 
  RENAME COLUMN "Payment Method" TO payment_method;
ALTER TABLE customer 
  RENAME COLUMN "Frequency of Purchases" TO frequency_of_purchases;

  --what is the total revenue generated by male vs female customers
select gender, SUM(purchase_amount) as revenue
 from customer
 group by gender;

 --which customer used discount but still spent more than average purchase amount?
 select customer_id,purchase_amount from customer 
 where discount_applied= 'Yes' and purchase_amount >= 
 (select avg(purchase_amount) from customer);

 --which are the top 5 product with highest average review rating?
 select item_purchased, 
 ROUND(avg(review_rating)::numeric,2) as average_product_rating
 from customer
 group by item_purchased
 order by avg(review_rating) desc
 limit 5;

 --Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, 
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM (
    SELECT 
        purchase_amount,
        CASE 
            WHEN ntile_rank = 1 THEN 'Young'
            WHEN ntile_rank = 2 THEN 'Adult'
            WHEN ntile_rank = 3 THEN 'Middle'
            WHEN ntile_rank = 4 THEN 'Senior'
        END AS age_group
    FROM (
        SELECT 
            purchase_amount,
            NTILE(4) OVER (ORDER BY age) AS ntile_rank
        FROM customer
    ) t
) x
GROUP BY age_group
ORDER BY total_revenue DESC;

 